### ISSUE TITLE
Configure widget in backend

### ISSUE THREAD

**Issue by allrude** [DominicWatts/Featured#1]
Hi I followed your instal instruction, but don't see the widget in the backend, so can't do "Configure widget in backend" 

what am I doing wrong? [ first doubt yourself before doubting someones code ;-) ]

**Comment by DominicWatts** [comment]
What version magento? I will check with your version.

**Comment by DominicWatts** [comment]
This is a vanilla 2.2.6 store with sample data I just spun up to check other module.  Option is showing.  So not sure.  Sorry.

![LM1RGj jpg](https://user-images.githubusercontent.com/7295705/61596869-b5b49900-ac00-11e9-8e5f-56fdab37187e.png)

![Screenshot-2019-7-21 Widgets New Widget Elements Content Magento Admin(1)](https://user-images.githubusercontent.com/7295705/61596884-e268b080-ac00-11e9-8614-3fc17dab52e9.png)

![Screenshot-2019-7-21 Widgets New Widget Elements Content Magento Admin](https://user-images.githubusercontent.com/7295705/61596885-e268b080-ac00-11e9-93ee-4c246491911d.png)
